name: Run Tests

on:  
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest
        #pytest --cov=./ --cov-report=xml
#     - name: Upload coverage report
#       uses: codecov/codecov-action@v1.0.6
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         file: ./coverage.xml
#         flags: unittests
